- name: populate package facts
  package_facts:

- name: Check for EFI directory
  ansible.builtin.stat:
    path: /sys/firmware/efi
    get_checksum: false
    get_mime: false
  register: efi_dir

- name: Set boot_mode fact
  ansible.builtin.set_fact:
    boot_mode: "{{ 'UEFI' if efi_dir.stat.exists else 'BIOS' }}"

- name: Slurp /etc/login.defs
  ansible.builtin.slurp:
    path: /etc/login.defs
  register: login_defs_raw
  no_log: true

- name: Decode login.defs content
  ansible.builtin.set_fact:
    login_defs: "{{ login_defs_raw.content | b64decode }}"
  no_log: true

- name: Slurp /etc/default/useradd
  ansible.builtin.slurp:
    src: /etc/default/useradd
  register: useradd_file
  no_log: true

- name: Set default_home_path
  ansible.builtin.set_fact:
    default_home_path: "{{ useradd_file.content
                        | b64decode
                        | regex_search('^HOME=(.*)$', '\\1', multiline=True)
                        | join(',') }}"

- name: Extract UID/SYS_UID ranges from login.defs
  ansible.builtin.set_fact:
    # sys_uid_min: "{{ login_defs | regex_search('^SYS_UID_MIN\\s+([0-9]+)', '\\1', multiline=True) | default(['201'], true) | first | int }}"
    sys_uid_max: "{{ login_defs | regex_search('^SYS_UID_MAX\\s+([0-9]+)', '\\1', multiline=True) | default(['999'], true) | first | int }}"
    uid_min: "{{ login_defs | regex_search('^UID_MIN\\s+([0-9]+)', '\\1', multiline=True) | default(['1000'], true) | first | int }}"
    # uid_max: "{{ login_defs | regex_search('^UID_MAX\\s+([0-9]+)', '\\1', multiline=True) | default(['60000'], true) | first | int }}"
    # sys_gid_min: "{{ login_defs | regex_search('^SYS_GID_MIN\\s+([0-9]+)', '\\1', multiline=True) | default(['201'], true) | first | int }}"
    sys_gid_max: "{{ login_defs | regex_search('^SYS_GID_MAX\\s+([0-9]+)', '\\1', multiline=True) | default(['999'], true) | first | int }}"
    gid_min: "{{ login_defs | regex_search('^GID_MIN\\s+([0-9]+)', '\\1', multiline=True) | default(['1000'], true) | first | int }}"
    # gid_max: "{{ login_defs | regex_search('^GID_MAX\\s+([0-9]+)', '\\1', multiline=True) | default(['60000'], true) | first | int }}"

- ansible.builtin.include_tasks: # noqa: name[missing]
    file: interactive_users.yml

- name: Print list of discovered interactive users
  ansible.builtin.debug:
    msg: "{{ interactive_user_list | map(attribute='key') | list | join(', ') }}"

- name: Create system account list
  ansible.builtin.set_fact:
    system_acct_list: "{{ system_acct_list | default([]) + [item] }}"
  loop: "{{ ansible_facts.getent_passwd | dict2items }}"
  no_log: true
  when:
    - item.value is sequence
    - item.value[1] | int <= ( sys_uid_max | int )

- name: Print list of discovered system accounts
  ansible.builtin.debug:
    msg: "{{ system_acct_list | map(attribute='key') | list | join(', ') }}"

- name: Get group account info
  ansible.builtin.getent:
    database: group
  register: getent_group

- name: Create non-system group list
  ansible.builtin.set_fact:
    nonsystem_group_list: "{{ nonsystem_group_list | default([]) + [item] }}"
  loop: "{{ ansible_facts.getent_group | dict2items }}"
  no_log: true
  when:
    - item.value is sequence
    - item.value[1] | int >= ( gid_min | int )

- name: Print list of discovered non-system groups
  ansible.builtin.debug:
    msg: "{{ nonsystem_group_list | map(attribute='key') | list | join(', ') }}"

- name: Create system group list
  ansible.builtin.set_fact:
    system_group_list: "{{ system_group_list | default([]) + [item] }}"
  loop: "{{ ansible_facts.getent_group | dict2items }}"
  no_log: true
  when:
    - item.value is sequence
    - item.value[1] | int <= ( sys_gid_max | int )

- name: Print list of discovered system groups
  ansible.builtin.debug:
    msg: "{{ system_group_list | map(attribute='key') | list | join(', ') }}"

- name: Deploy updated authselect profile templates
  ansible.builtin.template:
    src: "sssd/{{ item }}.j2"
    dest: /usr/share/authselect/default/{{ rhel9stig_stigrule_authselect_profile }}/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - password-auth
    - smartcard-auth
    - system-auth

# R-257778 RHEL-09-211015
- name: stigrule_257778__dnf_update
  ansible.builtin.dnf:
    name: '*'
    state: "{{ rhel9stig_stigrule_257778__dnf_State }}"
    update_cache: true
    skip_broken: true
    lock_timeout: 60
    update_only: true
  when: rhel9stig_stigrule_257778_Manage
  register: dnf_result
  retries: 10
  delay: 30
  until: dnf_result is succeeded

# R-257781 RHEL-09-211030
- name: Get current system default target
  ansible.builtin.command: systemctl get-default
  register: current_system_target
  changed_when: false
  when: rhel9stig_stigrule_257781_Manage

- name: stigrule_257781__set_system_default_target
  ansible.builtin.command: systemctl set-default {{ rhel9stig_stigrule_257781_target }}
  notify: reboot
  register: new_system_target
  changed_when: new_system_target.rc == 0
  when:
    - rhel9stig_stigrule_257781_Manage
    - current_system_target.stdout != rhel9stig_stigrule_257781_target

- name: Run pending handlers
  ansible.builtin.meta: flush_handlers

# R-257782 RHEL-09-211035
- name: stigrule_257782_ensure_rng-tools_installed
  ansible.builtin.package:
    name: rng-tools
    state: present
  when:
    - rhel9stig_stigrule_257782_Manage
    - not 'rng-tools' in ansible_facts.packages

- name: stigrule_257782_ensure_rngd_enabled
  ansible.builtin.service:
    name: rngd
    state: started
    enabled: true
  when:
    - rhel9stig_stigrule_257782_Manage

# R-257787 RHEL-09-212010
- name: Check for BIOS grub2_password
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      grep -iw grub2_password /boot/grub2/user.cfg || true
  register: grub_pass_check_bios
  changed_when: false
  no_log: true
  when:
    - rhel8STIG_stigrule_257787_Manage
    - boot_mode == "BIOS"

- name: stigrule_257787__grub2-setpassword_BIOS
  ansible.builtin.expect:
    command: grub2-setpassword
    responses:
      (?i)Password: "{{ rhel8STIG_stigrule_257787_grub_password }}"
      (?i)Confirm password: "{{ rhel8STIG_stigrule_257787_grub_password }}"
  no_log: true
  when:
    - rhel8STIG_stigrule_257787_Manage
    - boot_mode == "BIOS"
    - grub_pass_check_bios.stdout | length == 0
