namespace: usmcguy
name: stigs
version: 1.0.3
readme: README.md
authors:
  - Dave King (https://github.com/usmcguy)
  - Glenn Mora Rangel (https://github.com/glennmora)
description: Ansible Supplemental STIG Roles
license:
  - Apache-2.0
tags:
  - hardening
  - infrastructure
  - linux
  - security
  - stigs
dependencies:
  "ansible.posix": ">=2.0.0"
  "community.crypto": "<3.0.0"
  "community.general": "<12.0.0"
repository: "https://github.com/usmcguy/usmcguy.stigs"
