objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback:
    stig_xml_custom:
      description: Generate STIG results xml
      name: stig_xml_custom
      version_added: null
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.0.4
