- name: Ensure desired python3 installed # recommend python3.12+
  ansible.builtin.dnf:
    name: "{{ rhel8STIG_stigrule_python_version }}"
    state: installed
    update_cache: true
    skip_broken: true
    lock_timeout: 60

- name: Ensure desired python3 selected
  community.general.alternatives:
    name: python3
    path: /usr/bin/{{ rhel8STIG_stigrule_python_version }}
    link: /usr/bin/python3
    state: selected
