# Global vars
rhel9stig_allow_system_reboot: true
rhel9stig_stigrule_audit_tool_bins:
  - /usr/sbin/auditctl
  - /usr/sbin/auditd
  - /usr/sbin/ausearch
  - /usr/sbin/aureport
  - /usr/sbin/autrace
  - /usr/sbin/rsyslogd
  - /usr/sbin/augenrules
rhel9stig_stigrule_authselect_features:
  - with-faillock
  - with-files-access-provider
  - with-files-domain
  - with-mkhomedir
  - with-smartcard
  - with-smartcard-lock-on-removal
  - with-sudo
  - without-nullok
rhel9stig_stigrule_authselect_force: true
rhel9stig_stigrule_authselect_profile: sssd
rhel9stig_stigrule_authselect_dir: /var/log/faillock
rhel9stig_stigrule_logon_DenyAttempts: 3
rhel9stig_stigrule_login_FailInterval: 900
rhel9stig_stigrule_login_UnlockTime: 0
rhel9stig_stigrule_sssd_domain: fully.qualified.domain.name
rhel9stig_stigrule_sssd_id_provider: files
# R-257778 RHEL-09-211015
rhel9stig_stigrule_257778_Manage: true
rhel9stig_stigrule_257778__dnf_State: latest
# R-257781 RHEL-09-211030
rhel9stig_stigrule_257781_Manage: true
rhel9stig_stigrule_257781_target: 'multi-user.target'
# R-257782 RHEL-09-211035
rhel9stig_stigrule_257782_Manage: true
# R-257787 RHEL-09-212010
rhel9stig_stigrule_257787_Manage: true
rhel9stig_stigrule_257787_grub_password: ChangeMe_!@12#$34
# R-257788 RHEL-09-212015
rhel9stig_stigrule_257788_Manage: true
# R-257789 RHEL-09-212020
rhel9stig_stigrule_257789_Manage: true
rhel9stig_stigrule_257789_unique_name: grub_root
# V-257792 RHEL-09-212035
rhel9stig_stigrule_257792_Manage: true
# V-257793 RHEL-09-212040
rhel9stig_stigrule_257793_Manage: true
# V-257794 RHEL-09-212045
rhel9stig_stigrule_257794_Manage: true
# V-257795 RHEL-09-212050
rhel9stig_stigrule_257795_Manage: true
# V-257796 RHEL-09-212055
rhel9stig_stigrule_257796_Manage: true
# R-257817 RHEL-09-213110
rhel9stig_stigrule_257817_Manage: true
# R-257819 RHEL-09-214010
rhel9stig_stigrule_257819_Manage: true
rhel9stig_stigrule_257819_key_fingerprints:
  - name: Red Hat Release Key 2
    fingerprint: 567E 347A D004 4ADE 55BA  8A5F 199E 2F91 FD43 1D51
  - name: Red Hat Auxiliary Key 3
    fingerprint: 7E46 2425 8C40 6535 D56D  6F13 5054 E4A4 5A63 40B3
rhel9stig_stigrule_257819_src_key_path: roles/rhel9stig_supp/files/RPM-GPG-KEY-redhat-release
# R-257822 RHEL-09-214025
rhel9stig_stigrule_257822_Manage: true
# R-257826 RHEL-09-215015
rhel9stig_stigrule_257826_Manage: true
# R-257835 RHEL-09-215060
rhel9stig_stigrule_257835_Manage: true
rhel9stig_stigrule_257835_keep_tftp: true
# R-257837 RHEL-09-215070
rhel8STIG_stigrule_257837_Manage: true
# R-257843 RHEL-09-231010
rhel8STIG_stigrule_257843_Manage: true
# R-257844 RHEL-09-231015
rhel8STIG_stigrule_257844_Manage: true
# R-257845 RHEL-09-231020
rhel8STIG_stigrule_257845_Manage: true
# R-257846 RHEL-09-231025
rhel8STIG_stigrule_257846_Manage: true
# R-257847 RHEL-09-231030
rhel8STIG_stigrule_257847_Manage: true
# R-257848 RHEL-09-231035
rhel8STIG_stigrule_257848_Manage: true
# R-257850 RHEL-09-231045
rhel8STIG_stigrule_257850_Manage: true
# R-257851 RHEL-09-231050
rhel8STIG_stigrule_257851_Manage: true
# R-257852 RHEL-09-231055
rhel8STIG_stigrule_257852_Manage: true
# R-257854 RHEL-09-231065
rhel9stig_stigrule_257854_Manage: true
rhel9stig_stigrule_257854_ignore_paths: []
# R-257855 RHEL-09-231070
rhel9stig_stigrule_257855_Manage: true
rhel9stig_stigrule_257855_ignore_paths: []
# R-257856 RHEL-09-231075
rhel9stig_stigrule_257856_Manage: true
rhel9stig_stigrule_257856_ignore_paths: []
# R-257857 RHEL-09-231080
rhel9stig_stigrule_257857_Manage: true
rhel9stig_stigrule_257857_ignore_paths: []
# R-257858 RHEL-09-231085
rhel9stig_stigrule_257858_Manage: true
rhel9stig_stigrule_257858_ignore_paths: []
# R-257859 RHEL-09-231090
rhel9stig_stigrule_257859_Manage: true
rhel9stig_stigrule_257859_ignore_paths: []
# R-257860 RHEL-09-231095
rhel9stig_stigrule_257860_Manage: true
# R-257861 RHEL-09-231100
rhel9stig_stigrule_257861_Manage: true
# R-257862 RHEL-09-231105
rhel9stig_stigrule_257862_Manage: true
# R-257863 RHEL-09-231110
rhel9stig_stigrule_257863_Manage: true
# R-257864 RHEL-09-231115
rhel9stig_stigrule_257864_Manage: true
# R-257865 RHEL-09-231120
rhel9stig_stigrule_257865_Manage: true
# R-257866 RHEL-09-231125
rhel9stig_stigrule_257866_Manage: true
# R-257867 RHEL-09-231130
rhel9stig_stigrule_257867_Manage: true
# R-257868 RHEL-09-231135
rhel9stig_stigrule_257868_Manage: true
# R-257869 RHEL-09-231140
rhel9stig_stigrule_257869_Manage: true
# R-257870 RHEL-09-231145
rhel9stig_stigrule_257870_Manage: true
# R-257871 RHEL-09-231150
rhel9stig_stigrule_257871_Manage: true
# R-257872 RHEL-09-231155
rhel9stig_stigrule_257872_Manage: true
# R-257873 RHEL-09-231160
rhel9stig_stigrule_257873_Manage: true
# R-257874 RHEL-09-231165
rhel9stig_stigrule_257874_Manage: true
# R-257875 RHEL-09-231170
rhel9stig_stigrule_257875_Manage: true
# R-257876 RHEL-09-231175
rhel9stig_stigrule_257876_Manage: true
# R-257877 RHEL-09-231180
rhel9stig_stigrule_257877_Manage: true
# R-257878 RHEL-09-231180
rhel9stig_stigrule_257878_Manage: true
# R-257881 RHEL-09-231200
rhel9stig_stigrule_257881_Manage: true
rhel9stig_stigrule_257881_ignore_paths: []
# R-257882 RHEL-09-232010
rhel9stig_stigrule_257882_Manage: true
rhel9stig_stigrule_257882_ignore_paths: []
# R-257883 RHEL-09-232015
rhel9stig_stigrule_257883_Manage: true
rhel9stig_stigrule_257883_ignore_paths: []
# R-257884 RHEL-09-232020
rhel9stig_stigrule_257884_Manage: true
rhel9stig_stigrule_257884_ignore_paths: []
