# Global vars
rhel9stig_allow_system_reboot: true
rhel9stig_stigrule_audit_tool_bins:
  - /usr/sbin/auditctl
  - /usr/sbin/auditd
  - /usr/sbin/ausearch
  - /usr/sbin/aureport
  - /usr/sbin/autrace
  - /usr/sbin/rsyslogd
  - /usr/sbin/augenrules
rhel9stig_stigrule_authselect_features:
  - with-faillock
  - with-files-access-provider
  - with-files-domain
  - with-mkhomedir
  - with-smartcard
  - with-smartcard-lock-on-removal
  - with-sudo
  - without-nullok
rhel9stig_stigrule_authselect_force: true
rhel9stig_stigrule_authselect_profile: sssd
rhel9stig_stigrule_authselect_dir: /var/log/faillock
rhel9stig_stigrule_logon_DenyAttempts: 3
rhel9stig_stigrule_login_FailInterval: 900
rhel9stig_stigrule_login_UnlockTime: 0
rhel9stig_stigrule_sssd_domain: fully.qualified.domain.name
rhel9stig_stigrule_sssd_id_provider: files
# R-257778 RHEL-09-211015
rhel9stig_stigrule_257778_Manage: true
rhel9stig_stigrule_257778__dnf_State: latest
# R-257781 RHEL-09-211030
rhel9stig_stigrule_257781_Manage: true
rhel9stig_stigrule_257781_target: 'multi-user.target'
# R-257782 RHEL-09-211035
rhel9stig_stigrule_257782_Manage: true
# R-257787 RHEL-09-212010
rhel9stig_stigrule_257787_Manage: true
rhel9stig_stigrule_257787_grub_password: ChangeMe_!@12#$34
# R-257788 RHEL-09-212015
rhel9stig_stigrule_257788_Manage: true
# R-257789 RHEL-09-212020
rhel9stig_stigrule_257789_Manage: true
rhel9stig_stigrule_257789_unique_name: grub_root
# V-257792 RHEL-09-212035
rhel9stig_stigrule_257792_Manage: true
# V-257793 RHEL-09-212040
rhel9stig_stigrule_257793_Manage: true
# V-257794 RHEL-09-212045
rhel9stig_stigrule_257794_Manage: true
# V-257795 RHEL-09-212050
rhel9stig_stigrule_257795_Manage: true
